# Generated by Django 5.1.7 on 2025-06-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customclip_mix_mixtrack_mix_clips'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
